#!/usr/bin/env python3
"""Patch the buildozer.spec generated by pyside6-android-deploy.

Adds the app Python requirements (requests, pyjnius) and Android runtime
permissions (microphone, notifications, overlay, background) that the tool
does not expose via its own CLI.
"""
import re
import sys
from pathlib import Path

PERMISSIONS = [
    "android.permission.RECORD_AUDIO",
    "android.permission.INTERNET",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.SYSTEM_ALERT_WINDOW",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_MICROPHONE",
    "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
]

# PySide6 Android wheels are cp311-only; p4a defaults to 3.14 -> must pin 3.11
REQUIREMENTS = "python3==3.11.9,shiboken6,PySide6,requests,pyjnius"

PACKAGE_NAME = "classmate"
PACKAGE_DOMAIN = "edu.kwnc"
VERSION = "1.1"
INCLUDE_EXTS = "py,pyc,png,jpg,kv,atlas,ttf,qml,js,json"


def set_value(lines, key, value):
    out = []
    found = False
    for line in lines:
        m = re.match(r"^\s*([\w.]+)\s*=\s*(.*)$", line)
        if m and m.group(1) == key:
            out.append(f"{key} = {value}")
            found = True
        else:
            out.append(line)
    if not found:
        out.append(f"{key} = {value}")
    return out


def main():
    spec = Path("buildozer.spec")
    if not spec.exists():
        print("buildozer.spec not found", file=sys.stderr)
        sys.exit(1)
    lines = spec.read_text(encoding="utf-8").splitlines()
    lines = set_value(lines, "requirements", REQUIREMENTS)
    lines = set_value(lines, "android.permissions", ", ".join(PERMISSIONS))
    lines = set_value(lines, "package.name", PACKAGE_NAME)
    lines = set_value(lines, "package.domain", PACKAGE_DOMAIN)
    lines = set_value(lines, "version", VERSION)
    lines = set_value(lines, "source.include_exts", INCLUDE_EXTS)
    spec.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("[patch] requirements:", REQUIREMENTS)
    print("[patch] permissions:", ", ".join(PERMISSIONS))


if __name__ == "__main__":
    main()
